services:

  wordpress:
    image: wordpress:6.6.2-php8.3-apache
    ports:
      - 80:80

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
